### ISSUE TITLE
[QUESTION] Issue with cjs file

### ISSUE THREAD

**Issue by Lolispo** [awslabs/aws-jwt-verify#115]
**Question**
How can we help you?
I am struggling with this error when trying to run the tests for my code using the library
```
/home/petter/Tendium/odin-platinum-auth/node_modules/aws-jwt-verify/dist/cjs/jwt-rsa.js:322
        return new this(verifyProperties, additionalProperties?.jwksCache);
                                                               ^

SyntaxError: Unexpected token '.'
```

Library usage:
```

let cognitoJwtVerifier: CognitoJwtVerifierSingleUserPool<{
  clientId: string;
  tokenUse: "id" | "access" | null;
  userPoolId: string;
}>;
// Verifier that expects valid access tokens:
cognitoJwtVerifier = CognitoJwtVerifier.create({
  userPoolId: process.env.USER_POOL_ID,
  tokenUse: "access",
  clientId: process.env.CLIENT_ID,
});
   
{...}
decodedToken = await cognitoJwtVerifier.verify(activeToken);

```

**Versions**
Which version of `aws-jwt-verify` are you using? **3.4.0**
Version: **Node 16.17.0**
npm: 8.15.0
"typescript": "^4.9.5"

**Comment by ottokruse** [comment]
That's optional chaining you seem to be stumbling over, which has been supported by NodeJS since v14. Are you sure you're running it in NodeJS 16 ...?
Your code looks good otherwise.

**Comment by Lolispo** [comment]
```
>> node --version
v16.17.0`
>> npm run test

> @tendium/odin-platinum-auth@1.0.22 test
> mocha -r ts-node/register tests/**/*.test.ts --exit


/home/petter/Tendium/odin-platinum-auth/node_modules/aws-jwt-verify/dist/cjs/jwt-rsa.js:322
        return new this(verifyProperties, additionalProperties?.jwksCache);
                                                               ^

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
```

I feel stupid but can't understand why it would have an issue with optional chaining :/ Used a lot in other parts of the code, so it's just when using the dist/cjs/ js file that causes issues

**Comment by ottokruse** [comment]
What ts-node version is that? And share your tsconfig.json?

**Comment by Lolispo** [comment]
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "outDir": "dist",
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es2018",
    "declaration": true,
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "include": [
    "./src/**/*"
  ]
 }
 ```
 I tried `updating ts-node version now so tested it with 10.9.1 but still same issue :/ 
 
 Dependencies and devdependencies:
 ```
 "dependencies: {
    "aws-jwt-verify": "^3.4.0",
    "aws-sdk": "^2.804.0",
    "axios": "^0.19.2",
    "dotenv": "^8.2.0",
    "jsonwebtoken": "^8.5.1"
  },
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/chai": "^4.2.14",
    "@types/jsonwebtoken": "^9.0.1",
    "@types/mocha": "^5.2.7",
    "@types/npm": "^2.0.31",
    "@types/rewire": "^2.5.28",
    "@typescript-eslint/eslint-plugin": "^2.34.0",
    "@typescript-eslint/parser": "^2.34.0",
    "chai": "^4.2.0",
    "eslint": "^6.8.0",
    "mocha": "^10.2.0",
    "ncp": "^2.0.0",
    "node": "^13.14.0",
    "nyc": "^15.1.0",
    "rewire": "^4.0.1",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5"`
  ```

**Comment by ottokruse** [comment]
target es2018 might be it, try at least es2020

**Comment by Lolispo** [comment]
Tested with both es2020 and es2022, neither worked :/ Thanks for help but very confusing :(

**Comment by ottokruse** [comment]
Alas! Indeed very confusing.  Please create a reproducible  case for us. Ideally a GitHub repo with the minimum amount of code necessary to reproduce this.

**Comment by ottokruse** [comment]
Btw why also a dependency on `jsonwebtoken`? Because you're not getting `aws-jwt-verify` to work?

**Comment by Lolispo** [comment]
I will aim to to setup a reproducible state ASAP, but not fully able to prioritize it right now.
yes, dependency on jsonwebtoken is because I haven't been able to get it to work yet with the library.

**Comment by ottokruse** [comment]
Lol didn't know you could depend on node

Great it's solved now !
