### ISSUE TITLE
Package exports for '/node_modules/aws-jwt-verify' do not define a valid '.' target

### ISSUE THREAD

**Issue by madskunker** [awslabs/aws-jwt-verify#38]
Error: Package exports for '/node_modules/aws-jwt-verify' do not define a valid '.' target
  at resolveExportsTarget (internal/modules/cjs/loader.js:460:13)
  at resolveExports (internal/modules/cjs/loader.js:393:16)
  at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
  at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:29)
  at require (internal/modules/cjs/helpers.js:74:18)
  code: 'MODULE_NOT_FOUND'

Yes I have updated to the latest and I use 100's of npms.

**Comment by ottokruse** [comment]
Would you be so kind to leave us some instructions on how to reproduce this issue?

A quick google on the error suggests `rm -rf node_modules` and subsequent `npm install` might help out, but you're using 100's of npms so you have probably tried that!

**Comment by leelalagudu** [comment]
@madskunker  , following up on the above inquiry, could you update when you can please?

**Comment by ottokruse** [comment]
Closing because of inactivity, feel free to open a new issue
